"""empty message

Revision ID: 412924ccfdd6
Revises: cdbe81785b0d
Create Date: 2018-09-18 12:59:42.951043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412924ccfdd6'
down_revision = 'cdbe81785b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('climb', sa.Column('wall_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'climb', 'wall', ['wall_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'climb', type_='foreignkey')
    op.drop_column('climb', 'wall_id')
    # ### end Alembic commands ###
