"""empty message

Revision ID: 08f97f81bed3
Revises: febcc01cd728
Create Date: 2018-08-20 19:02:05.003976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f97f81bed3'
down_revision = 'febcc01cd728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dist_from_sx', sa.Float(), nullable=True),
    sa.Column('dist_from_bot', sa.Float(), nullable=True),
    sa.Column('holdType', sa.String(length=30), nullable=True),
    sa.Column('wall_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wall_id'], ['wall.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hold')
    # ### end Alembic commands ###
