"""empty message

Revision ID: 63adba4d5e64
Revises: 4910c3748489
Create Date: 2018-08-21 11:37:52.504969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63adba4d5e64'
down_revision = '4910c3748489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('climb', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('climb', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('climb', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('climb', 'status')
    op.drop_column('climb', 'start_time')
    op.drop_column('climb', 'end_time')
    # ### end Alembic commands ###
