"""empty message

Revision ID: 9ef80a7d9323
Revises: b46721bbe889
Create Date: 2018-09-04 20:32:28.807138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef80a7d9323'
down_revision = 'b46721bbe889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('climb_id', sa.Integer(), nullable=True))
    op.add_column('record', sa.Column('timestamp', sa.Integer(), nullable=True))
    op.add_column('record', sa.Column('x', sa.Float(), nullable=True))
    op.add_column('record', sa.Column('y', sa.Float(), nullable=True))
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.create_foreign_key(None, 'record', 'climb', ['climb_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.create_foreign_key(None, 'record', 'historic_hold', ['hold_id'], ['id'])
    op.drop_column('record', 'y')
    op.drop_column('record', 'x')
    op.drop_column('record', 'timestamp')
    op.drop_column('record', 'climb_id')
    # ### end Alembic commands ###
